name: 'dstll-diff'
description: 'Generate dstll diff'

inputs:
  pattern:
    description: 'File pattern to get diff for'
    required: true
    default: '*'

outputs:
  diff:
    description: "diff"
    value: ${{ steps.gen-diff.outputs.diff }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'dhth/dstll'
        path: 'temp/dstll'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1

    - name: go install
      shell: bash
      run: go install .
      working-directory: ./temp/dstll

    - name: Cleanup dstll directory
      shell: bash
      run: rm -rf temp

    - name: run dstll
      id: gen-diff
      shell: bash
      run: |
        dstll -h > diff.txt
        {
         echo 'diff<<EOF'
         cat diff.txt
         echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Delete diff file
      shell: bash
      run: rm diff.txt
