name: 'dstll-diff'
description: 'Generate dstll diff'

inputs:
  pattern:
    description: 'File pattern to get diff for'
    required: true
    default: '*'
  starting-commit:
    description: 'Starting commit for the diff'
    required: true
  ending-commit:
    description: 'Ending commit for the diff'
    required: true

outputs:
  diff:
    description: "diff"
    value: ${{ steps.gen-diff.outputs.diff }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'dhth/dstll'
        path: 'temp/dstll'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1

    - name: go install
      shell: bash
      run: go install .
      working-directory: ./temp/dstll

    - name: Cleanup dstll directory
      shell: bash
      run: rm -rf temp

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: run dstll
      id: gen-diff
      shell: bash
      env:
        PATTERN: ${{ inputs.directory }}
        STARTING_COMMIT: ${{ inputs.starting-commit }}
        ENDING_COMMIT: ${{ inputs.ending-commit }}
      run: |
        echo "diffing ${STARTING_COMMIT}..${ENDING_COMMIT} -- $PATTERN"
        dstll-diff diff.patch "$PATTERN" "$STARTING_COMMIT" "$ENDING_COMMIT"
        {
         echo 'diff<<EOF'
         cat diff.patch
         echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Delete diff file
      shell: bash
      run: rm diff.patch
