name: 'dstll-diff'
description: 'Generate dstll diff'

inputs:
  directory:
    description: 'Directory to operate in'
    required: true
  pattern:
    description: 'File pattern to get diff for'
    required: true
    default: '*'
  starting-commit:
    description: 'Starting commit for the diff'
    required: true
  ending-commit:
    description: 'Ending commit for the diff'
    required: true

outputs:
  diff:
    description: "diff"
    value: ${{ steps.gen-diff.outputs.diff }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'dhth/dstll'
        path: 'temp/dstll'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1

    - name: go install
      shell: bash
      run: go install .
      working-directory: ./temp/dstll

    - name: Cleanup dstll directory
      shell: bash
      run: rm -rf temp

    - name: run dstll
      id: gen-diff
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        PATTERN: ${{ inputs.directory }}
        STARTING_COMMIT: ${{ inputs.starting-commit }}
        ENDING_COMMIT: ${{ inputs.ending-commit }}
      run: |
        ./diff.sh "$PATTERN" "$STARTING_COMMIT" "$ENDING_COMMIT" diff.patch
        {
         echo 'diff<<EOF'
         cat diff.patch
         echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Delete diff file
      shell: bash
      run: rm diff.patch
